### ISSUE TITLE
Enabling columns in start-procmon.ps1

### ISSUE THREAD

**Issue by Bad3r** [jaapbrasser/Events#6]
Hi,
Can you please explain how to enable different columns in your script [Start-Procmon.ps1](https://github.com/jaapbrasser/Events/blob/master/TugaITLisbon2017/From%20zero%20to%20hero%20%E2%80%93%20Learn%20how%20to%20automate%20from%20the%20GUI/Start-Procmon.ps1)
I would like to enable the "Duration" column for example

**Comment by jaapbrasser** [comment]
Hello @Bad3r,

This is the script and the blog post I used when building the deck:
http://nomanualrequired.blogspot.com/2013/04/automating-process-monitor.html

As for enabling the Duration column, I haven't found a programmatic way of doing this. But if you would run procmon through the GUI once and select the columns you need you'll be able to do it programmatically from that point on.

I've taken a look at where the columns are stored, but when looking at `HKCU:\Software\Sysinternals\Process Monitor` the only value that changes is the ColumnCount property. But perhaps I am missing something there.

**Comment by Bad3r** [comment]
@jaapbrasser ,
Thank you for taking a look. I am aware of the work around by using the GUI which a good solution for now.
Unfortunately i think you are right and there is no way to enable it programmatically 

I appreciate you taking the time to check the issue
